// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'analytics_countries.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AnalyticsCountries _$AnalyticsCountriesFromJson(Map<String, dynamic> json) =>
    $checkedCreate(
      'AnalyticsCountries',
      json,
      ($checkedConvert) {
        $checkKeys(
          json,
          requiredKeys: const [
            'country',
            'city',
            'clicks',
            'leads',
            'sales',
            'saleAmount'
          ],
        );
        final val = AnalyticsCountries(
          country: $checkedConvert(
              'country',
              (v) => $enumDecode(_$AnalyticsCountriesCountryEnumEnumMap, v,
                  unknownValue:
                      AnalyticsCountriesCountryEnum.unknownDefaultOpenApi)),
          city: $checkedConvert(
              'city',
              (v) =>
                  $enumDecodeNullable(_$AnalyticsCountriesCityEnumEnumMap, v,
                      unknownValue:
                          AnalyticsCountriesCityEnum.unknownDefaultOpenApi) ??
                  AnalyticsCountriesCityEnum.star),
          clicks: $checkedConvert('clicks', (v) => v as num? ?? 0),
          leads: $checkedConvert('leads', (v) => v as num? ?? 0),
          sales: $checkedConvert('sales', (v) => v as num? ?? 0),
          saleAmount: $checkedConvert('saleAmount', (v) => v as num? ?? 0),
        );
        return val;
      },
    );

Map<String, dynamic> _$AnalyticsCountriesToJson(AnalyticsCountries instance) =>
    <String, dynamic>{
      'country': _$AnalyticsCountriesCountryEnumEnumMap[instance.country]!,
      'city': _$AnalyticsCountriesCityEnumEnumMap[instance.city]!,
      'clicks': instance.clicks,
      'leads': instance.leads,
      'sales': instance.sales,
      'saleAmount': instance.saleAmount,
    };

const _$AnalyticsCountriesCountryEnumEnumMap = {
  AnalyticsCountriesCountryEnum.AF: 'AF',
  AnalyticsCountriesCountryEnum.AL: 'AL',
  AnalyticsCountriesCountryEnum.DZ: 'DZ',
  AnalyticsCountriesCountryEnum.AS: 'AS',
  AnalyticsCountriesCountryEnum.AD: 'AD',
  AnalyticsCountriesCountryEnum.AO: 'AO',
  AnalyticsCountriesCountryEnum.AI: 'AI',
  AnalyticsCountriesCountryEnum.AQ: 'AQ',
  AnalyticsCountriesCountryEnum.AG: 'AG',
  AnalyticsCountriesCountryEnum.AR: 'AR',
  AnalyticsCountriesCountryEnum.AM: 'AM',
  AnalyticsCountriesCountryEnum.AW: 'AW',
  AnalyticsCountriesCountryEnum.AU: 'AU',
  AnalyticsCountriesCountryEnum.AT: 'AT',
  AnalyticsCountriesCountryEnum.AZ: 'AZ',
  AnalyticsCountriesCountryEnum.BS: 'BS',
  AnalyticsCountriesCountryEnum.BH: 'BH',
  AnalyticsCountriesCountryEnum.BD: 'BD',
  AnalyticsCountriesCountryEnum.BB: 'BB',
  AnalyticsCountriesCountryEnum.BY: 'BY',
  AnalyticsCountriesCountryEnum.BE: 'BE',
  AnalyticsCountriesCountryEnum.BZ: 'BZ',
  AnalyticsCountriesCountryEnum.BJ: 'BJ',
  AnalyticsCountriesCountryEnum.BM: 'BM',
  AnalyticsCountriesCountryEnum.BT: 'BT',
  AnalyticsCountriesCountryEnum.BO: 'BO',
  AnalyticsCountriesCountryEnum.BA: 'BA',
  AnalyticsCountriesCountryEnum.BW: 'BW',
  AnalyticsCountriesCountryEnum.BV: 'BV',
  AnalyticsCountriesCountryEnum.BR: 'BR',
  AnalyticsCountriesCountryEnum.IO: 'IO',
  AnalyticsCountriesCountryEnum.BN: 'BN',
  AnalyticsCountriesCountryEnum.BG: 'BG',
  AnalyticsCountriesCountryEnum.BF: 'BF',
  AnalyticsCountriesCountryEnum.BI: 'BI',
  AnalyticsCountriesCountryEnum.KH: 'KH',
  AnalyticsCountriesCountryEnum.CM: 'CM',
  AnalyticsCountriesCountryEnum.CA: 'CA',
  AnalyticsCountriesCountryEnum.CV: 'CV',
  AnalyticsCountriesCountryEnum.KY: 'KY',
  AnalyticsCountriesCountryEnum.CF: 'CF',
  AnalyticsCountriesCountryEnum.TD: 'TD',
  AnalyticsCountriesCountryEnum.CL: 'CL',
  AnalyticsCountriesCountryEnum.CN: 'CN',
  AnalyticsCountriesCountryEnum.CX: 'CX',
  AnalyticsCountriesCountryEnum.CC: 'CC',
  AnalyticsCountriesCountryEnum.CO: 'CO',
  AnalyticsCountriesCountryEnum.KM: 'KM',
  AnalyticsCountriesCountryEnum.CG: 'CG',
  AnalyticsCountriesCountryEnum.CD: 'CD',
  AnalyticsCountriesCountryEnum.CK: 'CK',
  AnalyticsCountriesCountryEnum.CR: 'CR',
  AnalyticsCountriesCountryEnum.CI: 'CI',
  AnalyticsCountriesCountryEnum.HR: 'HR',
  AnalyticsCountriesCountryEnum.CU: 'CU',
  AnalyticsCountriesCountryEnum.CY: 'CY',
  AnalyticsCountriesCountryEnum.CZ: 'CZ',
  AnalyticsCountriesCountryEnum.DK: 'DK',
  AnalyticsCountriesCountryEnum.DJ: 'DJ',
  AnalyticsCountriesCountryEnum.DM: 'DM',
  AnalyticsCountriesCountryEnum.DO: 'DO',
  AnalyticsCountriesCountryEnum.EC: 'EC',
  AnalyticsCountriesCountryEnum.EG: 'EG',
  AnalyticsCountriesCountryEnum.SV: 'SV',
  AnalyticsCountriesCountryEnum.GQ: 'GQ',
  AnalyticsCountriesCountryEnum.ER: 'ER',
  AnalyticsCountriesCountryEnum.EE: 'EE',
  AnalyticsCountriesCountryEnum.ET: 'ET',
  AnalyticsCountriesCountryEnum.FK: 'FK',
  AnalyticsCountriesCountryEnum.FO: 'FO',
  AnalyticsCountriesCountryEnum.FJ: 'FJ',
  AnalyticsCountriesCountryEnum.FI: 'FI',
  AnalyticsCountriesCountryEnum.FR: 'FR',
  AnalyticsCountriesCountryEnum.GF: 'GF',
  AnalyticsCountriesCountryEnum.PF: 'PF',
  AnalyticsCountriesCountryEnum.TF: 'TF',
  AnalyticsCountriesCountryEnum.GA: 'GA',
  AnalyticsCountriesCountryEnum.GM: 'GM',
  AnalyticsCountriesCountryEnum.GE: 'GE',
  AnalyticsCountriesCountryEnum.DE: 'DE',
  AnalyticsCountriesCountryEnum.GH: 'GH',
  AnalyticsCountriesCountryEnum.GI: 'GI',
  AnalyticsCountriesCountryEnum.GR: 'GR',
  AnalyticsCountriesCountryEnum.GL: 'GL',
  AnalyticsCountriesCountryEnum.GD: 'GD',
  AnalyticsCountriesCountryEnum.GP: 'GP',
  AnalyticsCountriesCountryEnum.GU: 'GU',
  AnalyticsCountriesCountryEnum.GT: 'GT',
  AnalyticsCountriesCountryEnum.GN: 'GN',
  AnalyticsCountriesCountryEnum.GW: 'GW',
  AnalyticsCountriesCountryEnum.GY: 'GY',
  AnalyticsCountriesCountryEnum.HT: 'HT',
  AnalyticsCountriesCountryEnum.HM: 'HM',
  AnalyticsCountriesCountryEnum.VA: 'VA',
  AnalyticsCountriesCountryEnum.HN: 'HN',
  AnalyticsCountriesCountryEnum.HK: 'HK',
  AnalyticsCountriesCountryEnum.HU: 'HU',
  AnalyticsCountriesCountryEnum.IS: 'IS',
  AnalyticsCountriesCountryEnum.IN: 'IN',
  AnalyticsCountriesCountryEnum.ID: 'ID',
  AnalyticsCountriesCountryEnum.IR: 'IR',
  AnalyticsCountriesCountryEnum.IQ: 'IQ',
  AnalyticsCountriesCountryEnum.IE: 'IE',
  AnalyticsCountriesCountryEnum.IL: 'IL',
  AnalyticsCountriesCountryEnum.IT: 'IT',
  AnalyticsCountriesCountryEnum.JM: 'JM',
  AnalyticsCountriesCountryEnum.JP: 'JP',
  AnalyticsCountriesCountryEnum.JO: 'JO',
  AnalyticsCountriesCountryEnum.KZ: 'KZ',
  AnalyticsCountriesCountryEnum.KE: 'KE',
  AnalyticsCountriesCountryEnum.KI: 'KI',
  AnalyticsCountriesCountryEnum.KP: 'KP',
  AnalyticsCountriesCountryEnum.KR: 'KR',
  AnalyticsCountriesCountryEnum.KW: 'KW',
  AnalyticsCountriesCountryEnum.KG: 'KG',
  AnalyticsCountriesCountryEnum.LA: 'LA',
  AnalyticsCountriesCountryEnum.LV: 'LV',
  AnalyticsCountriesCountryEnum.LB: 'LB',
  AnalyticsCountriesCountryEnum.LS: 'LS',
  AnalyticsCountriesCountryEnum.LR: 'LR',
  AnalyticsCountriesCountryEnum.LY: 'LY',
  AnalyticsCountriesCountryEnum.LI: 'LI',
  AnalyticsCountriesCountryEnum.LT: 'LT',
  AnalyticsCountriesCountryEnum.LU: 'LU',
  AnalyticsCountriesCountryEnum.MO: 'MO',
  AnalyticsCountriesCountryEnum.MG: 'MG',
  AnalyticsCountriesCountryEnum.MW: 'MW',
  AnalyticsCountriesCountryEnum.MY: 'MY',
  AnalyticsCountriesCountryEnum.MV: 'MV',
  AnalyticsCountriesCountryEnum.ML: 'ML',
  AnalyticsCountriesCountryEnum.MT: 'MT',
  AnalyticsCountriesCountryEnum.MH: 'MH',
  AnalyticsCountriesCountryEnum.MQ: 'MQ',
  AnalyticsCountriesCountryEnum.MR: 'MR',
  AnalyticsCountriesCountryEnum.MU: 'MU',
  AnalyticsCountriesCountryEnum.YT: 'YT',
  AnalyticsCountriesCountryEnum.MX: 'MX',
  AnalyticsCountriesCountryEnum.FM: 'FM',
  AnalyticsCountriesCountryEnum.MD: 'MD',
  AnalyticsCountriesCountryEnum.MC: 'MC',
  AnalyticsCountriesCountryEnum.MN: 'MN',
  AnalyticsCountriesCountryEnum.MS: 'MS',
  AnalyticsCountriesCountryEnum.MA: 'MA',
  AnalyticsCountriesCountryEnum.MZ: 'MZ',
  AnalyticsCountriesCountryEnum.MM: 'MM',
  AnalyticsCountriesCountryEnum.NA: 'NA',
  AnalyticsCountriesCountryEnum.NR: 'NR',
  AnalyticsCountriesCountryEnum.NP: 'NP',
  AnalyticsCountriesCountryEnum.NL: 'NL',
  AnalyticsCountriesCountryEnum.NC: 'NC',
  AnalyticsCountriesCountryEnum.NZ: 'NZ',
  AnalyticsCountriesCountryEnum.NI: 'NI',
  AnalyticsCountriesCountryEnum.NE: 'NE',
  AnalyticsCountriesCountryEnum.NG: 'NG',
  AnalyticsCountriesCountryEnum.NU: 'NU',
  AnalyticsCountriesCountryEnum.NF: 'NF',
  AnalyticsCountriesCountryEnum.MK: 'MK',
  AnalyticsCountriesCountryEnum.MP: 'MP',
  AnalyticsCountriesCountryEnum.NO: 'NO',
  AnalyticsCountriesCountryEnum.OM: 'OM',
  AnalyticsCountriesCountryEnum.PK: 'PK',
  AnalyticsCountriesCountryEnum.PW: 'PW',
  AnalyticsCountriesCountryEnum.PS: 'PS',
  AnalyticsCountriesCountryEnum.PA: 'PA',
  AnalyticsCountriesCountryEnum.PG: 'PG',
  AnalyticsCountriesCountryEnum.PY: 'PY',
  AnalyticsCountriesCountryEnum.PE: 'PE',
  AnalyticsCountriesCountryEnum.PH: 'PH',
  AnalyticsCountriesCountryEnum.PN: 'PN',
  AnalyticsCountriesCountryEnum.PL: 'PL',
  AnalyticsCountriesCountryEnum.PT: 'PT',
  AnalyticsCountriesCountryEnum.PR: 'PR',
  AnalyticsCountriesCountryEnum.QA: 'QA',
  AnalyticsCountriesCountryEnum.RE: 'RE',
  AnalyticsCountriesCountryEnum.RO: 'RO',
  AnalyticsCountriesCountryEnum.RU: 'RU',
  AnalyticsCountriesCountryEnum.RW: 'RW',
  AnalyticsCountriesCountryEnum.SH: 'SH',
  AnalyticsCountriesCountryEnum.KN: 'KN',
  AnalyticsCountriesCountryEnum.LC: 'LC',
  AnalyticsCountriesCountryEnum.PM: 'PM',
  AnalyticsCountriesCountryEnum.VC: 'VC',
  AnalyticsCountriesCountryEnum.WS: 'WS',
  AnalyticsCountriesCountryEnum.SM: 'SM',
  AnalyticsCountriesCountryEnum.ST: 'ST',
  AnalyticsCountriesCountryEnum.SA: 'SA',
  AnalyticsCountriesCountryEnum.SN: 'SN',
  AnalyticsCountriesCountryEnum.SC: 'SC',
  AnalyticsCountriesCountryEnum.SL: 'SL',
  AnalyticsCountriesCountryEnum.SG: 'SG',
  AnalyticsCountriesCountryEnum.SK: 'SK',
  AnalyticsCountriesCountryEnum.SI: 'SI',
  AnalyticsCountriesCountryEnum.SB: 'SB',
  AnalyticsCountriesCountryEnum.SO: 'SO',
  AnalyticsCountriesCountryEnum.ZA: 'ZA',
  AnalyticsCountriesCountryEnum.GS: 'GS',
  AnalyticsCountriesCountryEnum.ES: 'ES',
  AnalyticsCountriesCountryEnum.LK: 'LK',
  AnalyticsCountriesCountryEnum.SD: 'SD',
  AnalyticsCountriesCountryEnum.SR: 'SR',
  AnalyticsCountriesCountryEnum.SJ: 'SJ',
  AnalyticsCountriesCountryEnum.SZ: 'SZ',
  AnalyticsCountriesCountryEnum.SE: 'SE',
  AnalyticsCountriesCountryEnum.CH: 'CH',
  AnalyticsCountriesCountryEnum.SY: 'SY',
  AnalyticsCountriesCountryEnum.TW: 'TW',
  AnalyticsCountriesCountryEnum.TJ: 'TJ',
  AnalyticsCountriesCountryEnum.TZ: 'TZ',
  AnalyticsCountriesCountryEnum.TH: 'TH',
  AnalyticsCountriesCountryEnum.TL: 'TL',
  AnalyticsCountriesCountryEnum.TG: 'TG',
  AnalyticsCountriesCountryEnum.TK: 'TK',
  AnalyticsCountriesCountryEnum.TO: 'TO',
  AnalyticsCountriesCountryEnum.TT: 'TT',
  AnalyticsCountriesCountryEnum.TN: 'TN',
  AnalyticsCountriesCountryEnum.TR: 'TR',
  AnalyticsCountriesCountryEnum.TM: 'TM',
  AnalyticsCountriesCountryEnum.TC: 'TC',
  AnalyticsCountriesCountryEnum.TV: 'TV',
  AnalyticsCountriesCountryEnum.UG: 'UG',
  AnalyticsCountriesCountryEnum.UA: 'UA',
  AnalyticsCountriesCountryEnum.AE: 'AE',
  AnalyticsCountriesCountryEnum.GB: 'GB',
  AnalyticsCountriesCountryEnum.US: 'US',
  AnalyticsCountriesCountryEnum.UM: 'UM',
  AnalyticsCountriesCountryEnum.UY: 'UY',
  AnalyticsCountriesCountryEnum.UZ: 'UZ',
  AnalyticsCountriesCountryEnum.VU: 'VU',
  AnalyticsCountriesCountryEnum.VE: 'VE',
  AnalyticsCountriesCountryEnum.VN: 'VN',
  AnalyticsCountriesCountryEnum.VG: 'VG',
  AnalyticsCountriesCountryEnum.VI: 'VI',
  AnalyticsCountriesCountryEnum.WF: 'WF',
  AnalyticsCountriesCountryEnum.EH: 'EH',
  AnalyticsCountriesCountryEnum.YE: 'YE',
  AnalyticsCountriesCountryEnum.ZM: 'ZM',
  AnalyticsCountriesCountryEnum.ZW: 'ZW',
  AnalyticsCountriesCountryEnum.AX: 'AX',
  AnalyticsCountriesCountryEnum.BQ: 'BQ',
  AnalyticsCountriesCountryEnum.CW: 'CW',
  AnalyticsCountriesCountryEnum.GG: 'GG',
  AnalyticsCountriesCountryEnum.IM: 'IM',
  AnalyticsCountriesCountryEnum.JE: 'JE',
  AnalyticsCountriesCountryEnum.ME: 'ME',
  AnalyticsCountriesCountryEnum.BL: 'BL',
  AnalyticsCountriesCountryEnum.MF: 'MF',
  AnalyticsCountriesCountryEnum.RS: 'RS',
  AnalyticsCountriesCountryEnum.SX: 'SX',
  AnalyticsCountriesCountryEnum.SS: 'SS',
  AnalyticsCountriesCountryEnum.XK: 'XK',
  AnalyticsCountriesCountryEnum.unknownDefaultOpenApi:
      'unknown_default_open_api',
};

const _$AnalyticsCountriesCityEnumEnumMap = {
  AnalyticsCountriesCityEnum.star: '*',
  AnalyticsCountriesCityEnum.unknownDefaultOpenApi: 'unknown_default_open_api',
};
