// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'analytics_cities.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AnalyticsCities _$AnalyticsCitiesFromJson(Map<String, dynamic> json) =>
    $checkedCreate(
      'AnalyticsCities',
      json,
      ($checkedConvert) {
        $checkKeys(
          json,
          requiredKeys: const [
            'city',
            'country',
            'clicks',
            'leads',
            'sales',
            'saleAmount'
          ],
        );
        final val = AnalyticsCities(
          city: $checkedConvert('city', (v) => v as String),
          country: $checkedConvert(
              'country',
              (v) => $enumDecode(_$AnalyticsCitiesCountryEnumEnumMap, v,
                  unknownValue:
                      AnalyticsCitiesCountryEnum.unknownDefaultOpenApi)),
          clicks: $checkedConvert('clicks', (v) => v as num? ?? 0),
          leads: $checkedConvert('leads', (v) => v as num? ?? 0),
          sales: $checkedConvert('sales', (v) => v as num? ?? 0),
          saleAmount: $checkedConvert('saleAmount', (v) => v as num? ?? 0),
        );
        return val;
      },
    );

Map<String, dynamic> _$AnalyticsCitiesToJson(AnalyticsCities instance) =>
    <String, dynamic>{
      'city': instance.city,
      'country': _$AnalyticsCitiesCountryEnumEnumMap[instance.country]!,
      'clicks': instance.clicks,
      'leads': instance.leads,
      'sales': instance.sales,
      'saleAmount': instance.saleAmount,
    };

const _$AnalyticsCitiesCountryEnumEnumMap = {
  AnalyticsCitiesCountryEnum.AF: 'AF',
  AnalyticsCitiesCountryEnum.AL: 'AL',
  AnalyticsCitiesCountryEnum.DZ: 'DZ',
  AnalyticsCitiesCountryEnum.AS: 'AS',
  AnalyticsCitiesCountryEnum.AD: 'AD',
  AnalyticsCitiesCountryEnum.AO: 'AO',
  AnalyticsCitiesCountryEnum.AI: 'AI',
  AnalyticsCitiesCountryEnum.AQ: 'AQ',
  AnalyticsCitiesCountryEnum.AG: 'AG',
  AnalyticsCitiesCountryEnum.AR: 'AR',
  AnalyticsCitiesCountryEnum.AM: 'AM',
  AnalyticsCitiesCountryEnum.AW: 'AW',
  AnalyticsCitiesCountryEnum.AU: 'AU',
  AnalyticsCitiesCountryEnum.AT: 'AT',
  AnalyticsCitiesCountryEnum.AZ: 'AZ',
  AnalyticsCitiesCountryEnum.BS: 'BS',
  AnalyticsCitiesCountryEnum.BH: 'BH',
  AnalyticsCitiesCountryEnum.BD: 'BD',
  AnalyticsCitiesCountryEnum.BB: 'BB',
  AnalyticsCitiesCountryEnum.BY: 'BY',
  AnalyticsCitiesCountryEnum.BE: 'BE',
  AnalyticsCitiesCountryEnum.BZ: 'BZ',
  AnalyticsCitiesCountryEnum.BJ: 'BJ',
  AnalyticsCitiesCountryEnum.BM: 'BM',
  AnalyticsCitiesCountryEnum.BT: 'BT',
  AnalyticsCitiesCountryEnum.BO: 'BO',
  AnalyticsCitiesCountryEnum.BA: 'BA',
  AnalyticsCitiesCountryEnum.BW: 'BW',
  AnalyticsCitiesCountryEnum.BV: 'BV',
  AnalyticsCitiesCountryEnum.BR: 'BR',
  AnalyticsCitiesCountryEnum.IO: 'IO',
  AnalyticsCitiesCountryEnum.BN: 'BN',
  AnalyticsCitiesCountryEnum.BG: 'BG',
  AnalyticsCitiesCountryEnum.BF: 'BF',
  AnalyticsCitiesCountryEnum.BI: 'BI',
  AnalyticsCitiesCountryEnum.KH: 'KH',
  AnalyticsCitiesCountryEnum.CM: 'CM',
  AnalyticsCitiesCountryEnum.CA: 'CA',
  AnalyticsCitiesCountryEnum.CV: 'CV',
  AnalyticsCitiesCountryEnum.KY: 'KY',
  AnalyticsCitiesCountryEnum.CF: 'CF',
  AnalyticsCitiesCountryEnum.TD: 'TD',
  AnalyticsCitiesCountryEnum.CL: 'CL',
  AnalyticsCitiesCountryEnum.CN: 'CN',
  AnalyticsCitiesCountryEnum.CX: 'CX',
  AnalyticsCitiesCountryEnum.CC: 'CC',
  AnalyticsCitiesCountryEnum.CO: 'CO',
  AnalyticsCitiesCountryEnum.KM: 'KM',
  AnalyticsCitiesCountryEnum.CG: 'CG',
  AnalyticsCitiesCountryEnum.CD: 'CD',
  AnalyticsCitiesCountryEnum.CK: 'CK',
  AnalyticsCitiesCountryEnum.CR: 'CR',
  AnalyticsCitiesCountryEnum.CI: 'CI',
  AnalyticsCitiesCountryEnum.HR: 'HR',
  AnalyticsCitiesCountryEnum.CU: 'CU',
  AnalyticsCitiesCountryEnum.CY: 'CY',
  AnalyticsCitiesCountryEnum.CZ: 'CZ',
  AnalyticsCitiesCountryEnum.DK: 'DK',
  AnalyticsCitiesCountryEnum.DJ: 'DJ',
  AnalyticsCitiesCountryEnum.DM: 'DM',
  AnalyticsCitiesCountryEnum.DO: 'DO',
  AnalyticsCitiesCountryEnum.EC: 'EC',
  AnalyticsCitiesCountryEnum.EG: 'EG',
  AnalyticsCitiesCountryEnum.SV: 'SV',
  AnalyticsCitiesCountryEnum.GQ: 'GQ',
  AnalyticsCitiesCountryEnum.ER: 'ER',
  AnalyticsCitiesCountryEnum.EE: 'EE',
  AnalyticsCitiesCountryEnum.ET: 'ET',
  AnalyticsCitiesCountryEnum.FK: 'FK',
  AnalyticsCitiesCountryEnum.FO: 'FO',
  AnalyticsCitiesCountryEnum.FJ: 'FJ',
  AnalyticsCitiesCountryEnum.FI: 'FI',
  AnalyticsCitiesCountryEnum.FR: 'FR',
  AnalyticsCitiesCountryEnum.GF: 'GF',
  AnalyticsCitiesCountryEnum.PF: 'PF',
  AnalyticsCitiesCountryEnum.TF: 'TF',
  AnalyticsCitiesCountryEnum.GA: 'GA',
  AnalyticsCitiesCountryEnum.GM: 'GM',
  AnalyticsCitiesCountryEnum.GE: 'GE',
  AnalyticsCitiesCountryEnum.DE: 'DE',
  AnalyticsCitiesCountryEnum.GH: 'GH',
  AnalyticsCitiesCountryEnum.GI: 'GI',
  AnalyticsCitiesCountryEnum.GR: 'GR',
  AnalyticsCitiesCountryEnum.GL: 'GL',
  AnalyticsCitiesCountryEnum.GD: 'GD',
  AnalyticsCitiesCountryEnum.GP: 'GP',
  AnalyticsCitiesCountryEnum.GU: 'GU',
  AnalyticsCitiesCountryEnum.GT: 'GT',
  AnalyticsCitiesCountryEnum.GN: 'GN',
  AnalyticsCitiesCountryEnum.GW: 'GW',
  AnalyticsCitiesCountryEnum.GY: 'GY',
  AnalyticsCitiesCountryEnum.HT: 'HT',
  AnalyticsCitiesCountryEnum.HM: 'HM',
  AnalyticsCitiesCountryEnum.VA: 'VA',
  AnalyticsCitiesCountryEnum.HN: 'HN',
  AnalyticsCitiesCountryEnum.HK: 'HK',
  AnalyticsCitiesCountryEnum.HU: 'HU',
  AnalyticsCitiesCountryEnum.IS: 'IS',
  AnalyticsCitiesCountryEnum.IN: 'IN',
  AnalyticsCitiesCountryEnum.ID: 'ID',
  AnalyticsCitiesCountryEnum.IR: 'IR',
  AnalyticsCitiesCountryEnum.IQ: 'IQ',
  AnalyticsCitiesCountryEnum.IE: 'IE',
  AnalyticsCitiesCountryEnum.IL: 'IL',
  AnalyticsCitiesCountryEnum.IT: 'IT',
  AnalyticsCitiesCountryEnum.JM: 'JM',
  AnalyticsCitiesCountryEnum.JP: 'JP',
  AnalyticsCitiesCountryEnum.JO: 'JO',
  AnalyticsCitiesCountryEnum.KZ: 'KZ',
  AnalyticsCitiesCountryEnum.KE: 'KE',
  AnalyticsCitiesCountryEnum.KI: 'KI',
  AnalyticsCitiesCountryEnum.KP: 'KP',
  AnalyticsCitiesCountryEnum.KR: 'KR',
  AnalyticsCitiesCountryEnum.KW: 'KW',
  AnalyticsCitiesCountryEnum.KG: 'KG',
  AnalyticsCitiesCountryEnum.LA: 'LA',
  AnalyticsCitiesCountryEnum.LV: 'LV',
  AnalyticsCitiesCountryEnum.LB: 'LB',
  AnalyticsCitiesCountryEnum.LS: 'LS',
  AnalyticsCitiesCountryEnum.LR: 'LR',
  AnalyticsCitiesCountryEnum.LY: 'LY',
  AnalyticsCitiesCountryEnum.LI: 'LI',
  AnalyticsCitiesCountryEnum.LT: 'LT',
  AnalyticsCitiesCountryEnum.LU: 'LU',
  AnalyticsCitiesCountryEnum.MO: 'MO',
  AnalyticsCitiesCountryEnum.MG: 'MG',
  AnalyticsCitiesCountryEnum.MW: 'MW',
  AnalyticsCitiesCountryEnum.MY: 'MY',
  AnalyticsCitiesCountryEnum.MV: 'MV',
  AnalyticsCitiesCountryEnum.ML: 'ML',
  AnalyticsCitiesCountryEnum.MT: 'MT',
  AnalyticsCitiesCountryEnum.MH: 'MH',
  AnalyticsCitiesCountryEnum.MQ: 'MQ',
  AnalyticsCitiesCountryEnum.MR: 'MR',
  AnalyticsCitiesCountryEnum.MU: 'MU',
  AnalyticsCitiesCountryEnum.YT: 'YT',
  AnalyticsCitiesCountryEnum.MX: 'MX',
  AnalyticsCitiesCountryEnum.FM: 'FM',
  AnalyticsCitiesCountryEnum.MD: 'MD',
  AnalyticsCitiesCountryEnum.MC: 'MC',
  AnalyticsCitiesCountryEnum.MN: 'MN',
  AnalyticsCitiesCountryEnum.MS: 'MS',
  AnalyticsCitiesCountryEnum.MA: 'MA',
  AnalyticsCitiesCountryEnum.MZ: 'MZ',
  AnalyticsCitiesCountryEnum.MM: 'MM',
  AnalyticsCitiesCountryEnum.NA: 'NA',
  AnalyticsCitiesCountryEnum.NR: 'NR',
  AnalyticsCitiesCountryEnum.NP: 'NP',
  AnalyticsCitiesCountryEnum.NL: 'NL',
  AnalyticsCitiesCountryEnum.NC: 'NC',
  AnalyticsCitiesCountryEnum.NZ: 'NZ',
  AnalyticsCitiesCountryEnum.NI: 'NI',
  AnalyticsCitiesCountryEnum.NE: 'NE',
  AnalyticsCitiesCountryEnum.NG: 'NG',
  AnalyticsCitiesCountryEnum.NU: 'NU',
  AnalyticsCitiesCountryEnum.NF: 'NF',
  AnalyticsCitiesCountryEnum.MK: 'MK',
  AnalyticsCitiesCountryEnum.MP: 'MP',
  AnalyticsCitiesCountryEnum.NO: 'NO',
  AnalyticsCitiesCountryEnum.OM: 'OM',
  AnalyticsCitiesCountryEnum.PK: 'PK',
  AnalyticsCitiesCountryEnum.PW: 'PW',
  AnalyticsCitiesCountryEnum.PS: 'PS',
  AnalyticsCitiesCountryEnum.PA: 'PA',
  AnalyticsCitiesCountryEnum.PG: 'PG',
  AnalyticsCitiesCountryEnum.PY: 'PY',
  AnalyticsCitiesCountryEnum.PE: 'PE',
  AnalyticsCitiesCountryEnum.PH: 'PH',
  AnalyticsCitiesCountryEnum.PN: 'PN',
  AnalyticsCitiesCountryEnum.PL: 'PL',
  AnalyticsCitiesCountryEnum.PT: 'PT',
  AnalyticsCitiesCountryEnum.PR: 'PR',
  AnalyticsCitiesCountryEnum.QA: 'QA',
  AnalyticsCitiesCountryEnum.RE: 'RE',
  AnalyticsCitiesCountryEnum.RO: 'RO',
  AnalyticsCitiesCountryEnum.RU: 'RU',
  AnalyticsCitiesCountryEnum.RW: 'RW',
  AnalyticsCitiesCountryEnum.SH: 'SH',
  AnalyticsCitiesCountryEnum.KN: 'KN',
  AnalyticsCitiesCountryEnum.LC: 'LC',
  AnalyticsCitiesCountryEnum.PM: 'PM',
  AnalyticsCitiesCountryEnum.VC: 'VC',
  AnalyticsCitiesCountryEnum.WS: 'WS',
  AnalyticsCitiesCountryEnum.SM: 'SM',
  AnalyticsCitiesCountryEnum.ST: 'ST',
  AnalyticsCitiesCountryEnum.SA: 'SA',
  AnalyticsCitiesCountryEnum.SN: 'SN',
  AnalyticsCitiesCountryEnum.SC: 'SC',
  AnalyticsCitiesCountryEnum.SL: 'SL',
  AnalyticsCitiesCountryEnum.SG: 'SG',
  AnalyticsCitiesCountryEnum.SK: 'SK',
  AnalyticsCitiesCountryEnum.SI: 'SI',
  AnalyticsCitiesCountryEnum.SB: 'SB',
  AnalyticsCitiesCountryEnum.SO: 'SO',
  AnalyticsCitiesCountryEnum.ZA: 'ZA',
  AnalyticsCitiesCountryEnum.GS: 'GS',
  AnalyticsCitiesCountryEnum.ES: 'ES',
  AnalyticsCitiesCountryEnum.LK: 'LK',
  AnalyticsCitiesCountryEnum.SD: 'SD',
  AnalyticsCitiesCountryEnum.SR: 'SR',
  AnalyticsCitiesCountryEnum.SJ: 'SJ',
  AnalyticsCitiesCountryEnum.SZ: 'SZ',
  AnalyticsCitiesCountryEnum.SE: 'SE',
  AnalyticsCitiesCountryEnum.CH: 'CH',
  AnalyticsCitiesCountryEnum.SY: 'SY',
  AnalyticsCitiesCountryEnum.TW: 'TW',
  AnalyticsCitiesCountryEnum.TJ: 'TJ',
  AnalyticsCitiesCountryEnum.TZ: 'TZ',
  AnalyticsCitiesCountryEnum.TH: 'TH',
  AnalyticsCitiesCountryEnum.TL: 'TL',
  AnalyticsCitiesCountryEnum.TG: 'TG',
  AnalyticsCitiesCountryEnum.TK: 'TK',
  AnalyticsCitiesCountryEnum.TO: 'TO',
  AnalyticsCitiesCountryEnum.TT: 'TT',
  AnalyticsCitiesCountryEnum.TN: 'TN',
  AnalyticsCitiesCountryEnum.TR: 'TR',
  AnalyticsCitiesCountryEnum.TM: 'TM',
  AnalyticsCitiesCountryEnum.TC: 'TC',
  AnalyticsCitiesCountryEnum.TV: 'TV',
  AnalyticsCitiesCountryEnum.UG: 'UG',
  AnalyticsCitiesCountryEnum.UA: 'UA',
  AnalyticsCitiesCountryEnum.AE: 'AE',
  AnalyticsCitiesCountryEnum.GB: 'GB',
  AnalyticsCitiesCountryEnum.US: 'US',
  AnalyticsCitiesCountryEnum.UM: 'UM',
  AnalyticsCitiesCountryEnum.UY: 'UY',
  AnalyticsCitiesCountryEnum.UZ: 'UZ',
  AnalyticsCitiesCountryEnum.VU: 'VU',
  AnalyticsCitiesCountryEnum.VE: 'VE',
  AnalyticsCitiesCountryEnum.VN: 'VN',
  AnalyticsCitiesCountryEnum.VG: 'VG',
  AnalyticsCitiesCountryEnum.VI: 'VI',
  AnalyticsCitiesCountryEnum.WF: 'WF',
  AnalyticsCitiesCountryEnum.EH: 'EH',
  AnalyticsCitiesCountryEnum.YE: 'YE',
  AnalyticsCitiesCountryEnum.ZM: 'ZM',
  AnalyticsCitiesCountryEnum.ZW: 'ZW',
  AnalyticsCitiesCountryEnum.AX: 'AX',
  AnalyticsCitiesCountryEnum.BQ: 'BQ',
  AnalyticsCitiesCountryEnum.CW: 'CW',
  AnalyticsCitiesCountryEnum.GG: 'GG',
  AnalyticsCitiesCountryEnum.IM: 'IM',
  AnalyticsCitiesCountryEnum.JE: 'JE',
  AnalyticsCitiesCountryEnum.ME: 'ME',
  AnalyticsCitiesCountryEnum.BL: 'BL',
  AnalyticsCitiesCountryEnum.MF: 'MF',
  AnalyticsCitiesCountryEnum.RS: 'RS',
  AnalyticsCitiesCountryEnum.SX: 'SX',
  AnalyticsCitiesCountryEnum.SS: 'SS',
  AnalyticsCitiesCountryEnum.XK: 'XK',
  AnalyticsCitiesCountryEnum.unknownDefaultOpenApi: 'unknown_default_open_api',
};
